function ColorCardView(t)
  function DrawColor(ElevationColor,radius)
    import "android.graphics.drawable.GradientDrawable"
    local drawable=GradientDrawable()
    drawable.setColor(ElevationColor)
    drawable.setCornerRadius(radius)
    return drawable
  end
  local lay=loadlayout{
    FrameLayout;
    layout_height="fill";
    layout_width="fill";
    BackgroundDrawable=DrawColor(tonumber("0x01"..t.ElevationColor),t.radius);
    {
      LinearLayout;
      layout_height="fill";
      layout_width="fill";
      layout_marginTop="1.3dp";
      layout_marginLeft="1dp";
      layout_marginRight="1dp";
      BackgroundDrawable=DrawColor(tonumber("0x04"..t.ElevationColor),t.radius);
      {
        LinearLayout;
        layout_height="fill";
        layout_width="fill";
        layout_marginTop="1.3dp";
        layout_marginLeft="1dp";
        layout_marginRight="1dp";
        layout_marginBottom="0.9dp";
        BackgroundDrawable=DrawColor(tonumber("0x07"..t.ElevationColor),t.radius);
        {
          LinearLayout;
          layout_height="fill";
          layout_width="fill";
          layout_marginTop="1.3dp";
          layout_marginLeft="1dp";
          layout_marginRight="1dp";
          layout_marginBottom="0.9dp";
          BackgroundDrawable=DrawColor(tonumber("0x10"..t.ElevationColor),t.radius);
          {
            LinearLayout;
            layout_height="fill";
            layout_width="fill";
            layout_marginTop="1.3dp";
            layout_marginLeft="1dp";
            layout_marginRight="1dp";
            layout_marginBottom="0.9dp";
            BackgroundDrawable=DrawColor(tonumber("0x13"..t.ElevationColor),t.radius);
            {
              LinearLayout;
              layout_height="fill";
              layout_width="fill";
              layout_marginTop="1.3dp";
              layout_marginLeft="1dp";
              layout_marginRight="1dp";
              layout_marginBottom="0.9dp";
              BackgroundDrawable=DrawColor(tonumber("0x16"..t.ElevationColor),t.radius);
              {
                LinearLayout;
                layout_height="fill";
                layout_width="fill";
                layout_marginTop="1.3dp";
                layout_marginLeft="1dp";
                layout_marginRight="1dp";
                layout_marginBottom="0.9dp";
                BackgroundDrawable=DrawColor(tonumber("0x19"..t.ElevationColor),t.radius);
                {
                  LinearLayout;
                  layout_height="fill";
                  layout_width="fill";
                  layout_marginTop="1.3dp";
                  layout_marginLeft="1dp";
                  layout_marginRight="1dp";
                  layout_marginBottom="0.9dp";
                  BackgroundDrawable=DrawColor(tonumber("0x22"..t.ElevationColor),t.radius);
                  {
                    LinearLayout;
                    layout_height="fill";
                    layout_width="fill";
                    layout_marginTop="1.3dp";
                    layout_marginLeft="1dp";
                    layout_marginRight="1dp";
                    layout_marginBottom="0.9dp";
                    BackgroundDrawable=DrawColor(tonumber("0x25"..t.ElevationColor),t.radius);
                    {
                      LinearLayout;
                      layout_height="fill";
                      layout_width="fill";
                      layout_marginTop="1.3dp";
                      layout_marginLeft="1dp";
                      layout_marginRight="1dp";
                      layout_marginBottom="0.9dp";
                      BackgroundDrawable=DrawColor(tonumber("0x28"..t.ElevationColor),t.radius);
                      {
                        LinearLayout;
                        layout_height="fill";
                        layout_width="fill";
                        layout_marginTop="1.3dp";
                        layout_marginLeft="1dp";
                        layout_marginRight="1dp";
                        layout_marginBottom="0.9dp";
                        BackgroundDrawable=DrawColor(tonumber("0x31"..t.ElevationColor),t.radius);
                        {
                          LinearLayout;
                          layout_height="fill";
                          layout_width="fill";
                          layout_marginTop="1.3dp";
                          layout_marginLeft="1dp";
                          layout_marginRight="1dp";
                          layout_marginBottom="0.9dp";
                          BackgroundDrawable=DrawColor(tonumber("0x34"..t.ElevationColor),t.radius);
                          {
                            LinearLayout;
                            layout_height="fill";
                            layout_width="fill";
                            layout_marginTop="1.3dp";
                            layout_marginLeft="1dp";
                            layout_marginRight="1dp";
                            layout_marginBottom="0.9dp";
                            BackgroundDrawable=DrawColor(tonumber("0x37"..t.ElevationColor),t.radius);
                            {
                              LinearLayout;
                              layout_height="fill";
                              layout_width="fill";
                              layout_marginTop="1.3dp";
                              layout_marginLeft="1dp";
                              layout_marginRight="1dp";
                              layout_marginBottom="0.9dp";
                              BackgroundDrawable=DrawColor(tonumber("0x40"..t.ElevationColor),t.radius);
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return function() return lay end
end