appname="支付宝"
appver="1.0"
appcode="1"
appsdk="20"
path_pattern=""
packagename="com.gteam.zfbzb"
theme="Theme_DeviceDefault_Light_NoActionBar"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
