appname="Xv7"
appver="1.0"
appcode="1"
appsdk="15"
path_pattern=""
packagename="com.GTeam.Xv"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
